"""add_name_card_images_table

Revision ID: 1cfddae12df2
Revises: a70d42ed3c54
Create Date: 2026-03-04 21:42:23.564730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfddae12df2'
down_revision: Union[str, Sequence[str], None] = 'a70d42ed3c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_card_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_card_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['name_card_id'], ['name_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('name_cards', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('name_cards', sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('name_card_images')
    # ### end Alembic commands ###
